# fly.toml app configuration file generated for notetakerforall on 2023-06-17T02:11:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notetakerforall"
primary_region = "yyz"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
