# fly.toml app configuration file generated for notetakerfrontend on 2023-06-17T03:07:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "notetakerfrontend"
primary_region = "yyz"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
